### ISSUE TITLE
Sub resources should provide all options (remote_file, cookbook_file, template)

### ISSUE THREAD

**Issue by bbaugher** [cerner/cerner_tomcat#4]

**Comment by EdwardSkoviak** [comment]
Theres a few options on how we can actually tackle this, the simplest approach involves dropping the dsl and doing an instance_eval on the file's block within the respective file resource (i.e. template, cookbook_file, remote_file), similiar to what I've done [here](https://github.com/cerner/cerner_tomcat/blob/69b09087c1faf5caa6da99030e89560c8f80ac9f/libraries/web_app.rb#L73-L76).

For funsies, since I wanted to play with Poise, I tackled an improved approach utilizing an HWRP and the sub-resource functionality in [Poise](https://github.com/poise/poise). With this approach, these are true sub-resources and are capable of standing on their own, e.g:

```
cerner_tomcat 'test_instance' do
  user 'test_user'
  ...
  remote_file 'test_file' do
    source 'http://...'
  end
end

cerner_tomcat_remote_file 'test_file_2' do
  parent 'test_instance'
  source 'http://..."
end
```

Both remote_file blocks above are powered by the same underlying sub-resource. The cerner_tomcat_remote_file resource simply extends chef's remote_file resource, and the only additional functionality is to use an optional parent resource's user, group, and install dir as the base dir. If no parent is defined it behaves identical to a standard remote_file resource. The parent is automatically added in when calling the (cerner_tomcat)remote_file resource as a sub-resource of a cerner_tomcat resource block.

A difference worth noting here is the sub-resources aren't actually evaluated until _after_ the cerner_tomcat parent resource completes. This led to a slight redesign on how the service daemon is handled (and two new actions on the cerner_tomcat resource), which gave the added benefit where we can notify a service restart externally. Poise also has an improvement to `use_inline_resources` which is the [notifying block](https://github.com/poise/poise#notifying-block). With the notifying block delayed actions (such as the service restart) are executed at the end of the main converge vs the end of the inner converge. This avoids the service restarting multiple times during convergence.

Theres a few other changes that ended up getting rolled in as well, such as using poise-archive to handle extracting our tomcat archive, adding in better support for the sensitive param on the parent resource with a 'true' default (sub-resources also default to the parent's value, but can be overridden), removed the whole `start_on_install` concept which seemed to have no value (unless I'm overlooking something, a restart looked to be guaranteed), setting the created user/group as a system user/group, and probably some other changes I'm not remembering off the top of my head.

Anyway I've had my fun and most of the work is done, but theres still more polishing to complete it out, but first I wanted to push the work out to see if theres support for me wrapping this up before moving forward. I dumped the chef spec tests since the DSL blocks are mostly gone (health check is still around), but the integration tests are pretty-much untouched and pass just fine. Please take a look and see what you think:

https://github.com/cerner/cerner_tomcat/tree/poise

**Comment by bbaugher** [comment]
Overall I like it. Seems to simplify a lot of things while provide the new functionality and others. Your re-wiring code scares me and I generally have no idea what its doing

**Comment by EdwardSkoviak** [comment]
Haha, yea the rewiring stuff i have to go through and clean up, I basically just copy/pasted that from the poise application cookbook[1]. The gist of why i copied it over is to make it so when the cerner_tomcat_remote_file resource is called as a sub-resource of cerner_tomcat, you don't have to call cerner_tomcat_remote_file but can simply use remote_file. i need to figure out how that works and get only what I need.

[1] https://github.com/poise/application/blob/master/lib/poise_application/resources/application.rb#L107-L187

**Comment by bbaugher** [comment]
Completed by #34

**Comment by cchesser** [comment]
>  removed the whole start_on_install concept which seemed to have no value (unless I'm overlooking something, a restart looked to be guaranteed), setting the created user/group as a system user/group, and probably some other changes I'm not remembering off the top of my head.

Was doing some tests in uplifting to the 3.0.0 release, and I can confirm the `start_on_install` isn't needed anymore with your changes. Previously with the service installation, it would start, and then have a delayed restart, which would always have two service start events on a fresh install (which can add quite a bit of time on an install). This was added in #16, which did allow avoiding both an immediate start and then delayed restart.
