### ISSUE TITLE
Java installation fails if `java::notify` recipe has been included before `cerner_tomcat` resource

### ISSUE THREAD

**Issue by nibroc** [cerner/cerner_tomcat#44]
We're running into a strange issue where `cerner_tomcat` will fail if the `java::notify` recipe has been pulled in before `cerner_tomat` is first used. For example:

```
include_recipe 'java::notify'

ruby_block 'test missing resource' do
  block do
    Chef::Log.info "The block in test missing resource was reached!"
  end
  action :run
  notifies :write, 'log[jdk-version-changed]', :immediately
end

cerner_tomcat 'server-8080' do
  install_java true
end
```

When this recipe runs, the ruby block will execute fine, and the `log[jdk-version-changed]` notification will trigger as expected. Immediately after though, when `cerner_tomcat` includes `java::default`, the java resource will fail to notify `log[jdk-version-changed]` saying it doesn't exist. 

In the same Chef run, you can see the ruby_block successfully find the resource:

       Recipe: chef_broken::default
         * ruby_block[test missing resource] action run[2017-04-04T12:18:54-05:00] INFO: Processing ruby_block[test missing resource] action run (chef_broken::default line 3)
       [2017-04-04T12:18:54-05:00] DEBUG: Providers for generic ruby_block resource enabled on node include: [Chef::Provider::RubyBlock]
       [2017-04-04T12:18:54-05:00] DEBUG: Provider for action run on resource ruby_block[test missing resource] is Chef::Provider::RubyBlock
       [2017-04-04T12:18:54-05:00] INFO: The block in test missing resource was reached!
       [2017-04-04T12:18:54-05:00] INFO: ruby_block[test missing resource] called
       
           - execute the ruby block test missing resource
       [2017-04-04T12:18:54-05:00] INFO: ruby_block[test missing resource] sending write action to log[jdk-version-changed] (immediate)
       Recipe: java::notify
         * log[jdk-version-changed] action write[2017-04-04T12:18:54-05:00] INFO: Processing log[jdk-version-changed] action write (java::notify line 29)

But then almost immediately after, the resource is gone:

```
          ================================================================================
           Error executing action `enable` on resource 'cerner_tomcat[server-8080]'
           ================================================================================
           
           Chef::Exceptions::ResourceNotFound
           ----------------------------------
           resource yum_package[java-1.6.0-openjdk] is configured to notify resource log[jdk-version-changed] with action write, but log[jdk-version-changed] cannot be found in the resource collection. yum_package[java-1.6.0-openjdk] is defined in /tmp/kitchen/cache/cookbooks/java/recipes/openjdk.rb:54:in `block in from_file'
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource.rb:80:in `block in resolve_notification_references'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource.rb:79:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource.rb:79:in `resolve_notification_references'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:101:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:100:in `converge'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
           /tmp/kitchen/cache/cookbooks/cerner_tomcat/libraries/cerner_tomcat.rb:136:in `action_enable'
```

Oddly, if the `include_recipe 'java::notify'` is removed, the `cerner_tomcat` consumption of `java` is successful. I don't quite understand where the `log[jdk-version-changed]` resource is disappearing to, but it's definitely in the resource registry before `cerner_tomcat` since the `ruby_block` can find it.

**Comment by EdwardSkoviak** [comment]
I'll take a stab at providing an explanation for what the problem is, but this isn't due to a bug within cerner_tomcat. It does, however, unveil the underlying code smell of the cerner_tomcat provider having the option to trigger an include_recipe. It's easy for consumers to end up having a bad time.

What you are running into are implementation details of the chef execution model. During the chef-client compilation phase, compilation happens for the root run_context only, no resource provider code is executed. The chef-client converge then starts on the root run_context. As you see in the output above, the include_recipe is then run. It's important to note here that recipes can only be included **once** during chef-client execution. The ruby block is then converged and has access to the root context and is able to notify the `log[jdk-version-changed]` resource that was created by the `java::notify` recipe.

Now the cerner_tomcat resource provider compilation happens, followed by the convergence on its sub-context. Here, inside the sub-context, the java recipe is included. As you noticed here[1] within the openjdk recipe, it too is attempting to include the recipe for `java::notify`, but oops, its already been included earlier in the execution, so that code is a no-op.

Convergence continues and the openjdk recipe now attempts to notify[2] the `log[jdk-version-changed]` resource. Since the `java::notify` recipe wasn't included during the resource provider's converge, this resource does not exist in the sub_context. Thus, the ResourceNotFound exception above.

If you want to include the `java::notify` recipe outside of the cerner_tomcat resource provider, then you will need to include the `java` recipe outside as well. You can then set install_java option to false, but as you learned above it's a no-op so it shouldn't be necessary for a successful converge.

[1] https://github.com/agileorbit-cookbooks/java/blob/master/recipes/openjdk.rb#L22
[2] https://github.com/agileorbit-cookbooks/java/blob/master/recipes/openjdk.rb#L55

**Comment by nibroc** [comment]
That's interesting. So it's effectively like the set of recipes that has already been included is global, but the resources provided by recipes is scoped to the context, and the way the cerner_tomcat provider works, it's technically in a different context?

I knew there's a simple work around in just including `java` myself, but I was hoping it was something that could be fixed since I was hoping I could just use the parameter and not have to worry about pulling that config out myself in the wrapper cookbook. Anyway, thanks for the explanation! That's certainly an interesting quirk.

**Comment by EdwardSkoviak** [comment]
Basically, yes, and it's a quirk of all LWRPs in chef.  If you're curious read up on use_inline_resources and updated_by_last_action.

When you say you didn't want to have to pull that config out yourself, what are you referring to? It should only be a two line difference in your wrapper with include_recipe outside and install_java set to false on the resource.

Assuming you're a Cerner associate, reach out to me on the internal Slack if you want any help. If not, feel free to post back here.

**Comment by nibroc** [comment]
That's all I meant. I was just being lazy and trying to keep my wrapper purely configuration piped into cerner_tomcat. Thanks!
