### ISSUE TITLE
Kill process when it doesn't stop cleanly and gather information

### ISSUE THREAD

**Issue by bbaugher** [cerner/cerner_tomcat#5]

**Comment by Ansonator** [comment]
This is the most annoying issue in tomcat for us.  Frequently, an application causes tomcat to refuse to shut down.  It appears to be because tomcat thinks there is a possible memory leak and then refuses to terminate some threads.  I've seen it happen with Lift Framework, Scala (Akka), and now Jersey.  We eventually find a fix in the application, but that usually requires a lot of digging and the problem is likely to return at some point when we modify or deploy a new application.

The problem with forcibly killing tomcat is that it sometimes won't redeploy our apps when it is restarted.  So, we sometimes need to kill tomcat and nuke our application directories in webapps.  So, I think the cookbook should also delete the app directories whenever the kill option is used.

Also, I'm wondering if anyone has found a way to configure tomcat so that it shuts down even if there are possible leaking threads.  If tomcat would terminate itself, that would be better.

**Comment by cchesser** [comment]
I plan on pushing out a proposed change for this, which introduces a diagnostic feature of the service script. We have encountered several cases where we cannot shutdown the JVM, and generally the scenario that we encounter is a web application has started a thread pool with a non-daemon thread, which ultimately is blocking the shutdown. While we have been pushing consumers to fix their code, it would be nice of this to capture diagnostics and still shutdown (as we are just having a human then interact with this and force kill it).

My plan is to update the init script to capture diagnostics of the JVM once shutdown has reached a "timeout" scenario of attempts. It will then dump a set of diagnostics of the process into /tmp (which will be a tar.gz) and then will forcibly shut down the process (via a SIGKILL). This will then also be a `diagnostic` option on the script (like `health`, `status`), where you can capture this diagnostic bundle on demand if needed.

**Comment by bbaugher** [comment]
+1

**Comment by cchesser** [comment]
Started applying this, and noticed that `catalina.sh` already has similar logic with their `-force` option on the `stop` command, where it will include the thread dump on stdout at the point of having to then issue a `SIGKILL`. To leverage this, it would remove some of our logic in `stop` and defer to the stop command to handle it.

My plan was to update the cookbook to define the location of `CATALINA_PID` to support this behavior (it is an optional configuration, which tells the location of a file that hosts the PID), and then delegate our timeout configuration to the `-force` option. With this, I will include the `diagnostic` option since it was helpful to also to include to further diagnose the JVM.

```
stop n -force     Stop Catalina, wait up to n seconds and then use kill -KILL if still running
```

**Comment by EdwardSkoviak** [comment]
If we make the switch to upstart it would handle doing a SIGKILL if the service isn't responding to a SIGTERM. For peace of mind, I did a little digging in and not using the in-band shutdown looks to be okay since the shutdown hooks will respond to the SIGTERM. Looks to be considered an better approach since the tomcat shutdown port is insecure, and apparently dates back to before things like Upstart and systemd.

**Comment by cchesser** [comment]
I apologize on the late reply. I would be fine with still including this, so those which continue using the default (`sysvinit`) can still get this, and the tooling for capturing other JVM metrics. I will push a PR out for this today which we can then discuss how much we want included, based on the enhancements offered with #22.

**Comment by cchesser** [comment]
Added a PR for this changed, based on the 3.x line: #39. I will be happy to also make this available in the 2.x release line, if we think there is a demand for it (I know I'm still using the 2.x).

**Comment by bbaugher** [comment]
Done by #39

**Comment by cchesser** [comment]
@bbaugher, any interest in keeping a 2.x release of this? I tried upgrading to 3.x and ran into some snags (looks like a ulimit issue on the point of WAR extraction, where the acting user is different - looks to be the user for Tomcat). I haven't had a chance to dig in further, but could benefit of this change on my current 2.x usage.

**Comment by bbaugher** [comment]
I'd be fine supporting that. Not sure if I will have time soon to port it over to 2.x

**Comment by cchesser** [comment]
I can do the port. Do you want to create a `2.x` branch which will be the release point for anything 2.x?

**Comment by bbaugher** [comment]
Yes thats probably something I should have done after saying that, https://github.com/cerner/cerner_tomcat/tree/2.x

**Comment by cchesser** [comment]
I finally got to patching this back to 2.x: #45
